### ISSUE TITLE
codeCoverageReport is skipped with JUnit5

### ISSUE THREAD

**Issue by benwicks** [codecov/example-gradle#6]
When I run `gradle codeCoverageReport` on my project with exclusively JUnit5 tests, I get:
```
> Task :codeCoverageReport
Skipping task ':codeCoverageReport' as task onlyIf is false.
```
When I run `gradle test`, I get test results from my JUnit5 tests in the `/build/test-results/junit-platform/` directory.

I could use some help isolating the problem. Do you know why this doesn't work? Thank you.

**Comment by benwicks** [comment]
I see [this issue](https://github.com/gradle/gradle/issues/1037) that looks blocked by a next gradle release.

**Comment by stevepeak** [comment]
Thank you for reporting. This issue appears to be concerning Gradle and not Codecov. I'm not sure what help we can provide here....

**Comment by benwicks** [comment]
That's okay. I will continue to monitor the gradle issue. Thanks for the reply!
